### ISSUE TITLE
Failed to build Lua example

### ISSUE THREAD

**Issue by rinthel** [billyquith/ponder#104]
Hello, I've used ponder 2.1.1 in my project, and I appreciate that it is very useful for me.
And recently I found that the major upgrade happened.
It's very grad to hear, but I've failed to build the lua example with the PONDER_USING_LUA option on my mac. The error was that some kind of `FTrait::ReturnType` was missed during the instantiation of the template class for `ponder::Class::declare().function()`.
How can I build the Lua example successfully?
Thank you for reading.

**Comment by billyquith** [comment]
Grrr, 🐱 but I help! 🐾

**Comment by billyquith** [comment]
Fixed.
