### ISSUE TITLE
missing a return statement in string_view.hpp at line 215

### ISSUE THREAD

**Issue by shierei** [billyquith/ponder#106]
My compiler options turned on -we1011 and caught this one.

ponder/detail/string_view.hpp(215): error #1011: missing return statement at end of non-void function "ponder::detail::basic_string_view<CharT, Traits>::copy"
      }

    size_type copy(CharT* dest, size_type count, size_type pos = 0) const
    {
        if (pos >= size()) { throw std::out_of_range("basic_string_view::copy out of range"); }
        for (int i = 0; i < size();++i)
        {
            dest[i] = operator[](i + pos);
        }
    }

**Comment by billyquith** [comment]
Fixed.
