### ISSUE TITLE
Interest for registration of template types?

### ISSUE THREAD

**Issue by lhamot** [billyquith/ponder#111]
Hi!
Let's say I have this kind of code to reflect with ponder:
```cpp
template<typename T>
struct TmplStruct{
	T field1;
};
struct UseTmplStruct{
	TmplStruct<int> tmplField;
};
```
I wrote a macro to register template type with one template parameter:
```cpp
#define PONDER_AUTO_TYPE_TMPL1(TYPE, REGISTER_FN) \
    namespace ponder { \
        namespace detail { \
            template <typename T1> struct StaticTypeId<TYPE<T1> > { \
                static const char* get(bool checkRegister = true) { \
					static char name[256]; \
					snprintf(name, 256, "%s<%s>", #TYPE, typeid(T1).name()); \
                    if (checkRegister) \
                        detail::ensureTypeRegistered(name, REGISTER_FN<T1>); \
                    return name; \
                } \
                static constexpr bool defined = true, copyable = true; \
            }; \
        } \
    }
```

The reflection is done with this code:
```cpp
PONDER_AUTO_TYPE_TMPL1(TmplStruct, declare_TmplStruct);
template<typename T1>
static void declare_TmplStruct(){
    ponder::Class::declare<TmplStruct<T1> >()
        .property("field1", &TmplStruct<T1>::field1);
}

PONDER_AUTO_TYPE(UseTmplStruct, declare_UseTmplStruct);
static void declare_UseTmplStruct(){
    ponder::Class::declare<UseTmplStruct>()
        .property("tmplField", &UseTmplStruct::tmplField);
}
```

This allow me to use this type in this way:
```cpp
UseTmplStruct useTmpl;
ponder::UserObject useTmplR(&useTmpl);
useTmplR.set("tmplField", NS::TmplStruct<int>{12});
```

So, the questions are:
- Is there a macro like *PONDER_AUTO_TYPE_TMPL1* in ponder which I didn't see?
- If not, why? It seams to be useful in some cases (when a concrete type is used in a field which is reflected)
- Are you interested into this?
- If yes, do you want I create a pull request?

**Comment by billyquith** [comment]
You can use [`PONDER_TYPE()`](https://billyquith.github.io/ponder/pondertype_8hpp.html#aee5005c7943f3506b239d987821d5486) for this purpose. You have to explicitly declare the type. There is no "auto" version. This macro works with any number of parameters.

I could perhaps make this more prominent in the docs.

**Comment by lhamot** [comment]
Thank you for your answer.

With `PONDER_TYPE()`, I have to call it once by concrete type, isn't it?
For example:
```
PONDER_TYPE(TmplStruct<int>);
PONDER_TYPE(TmplStruct<short>);
PONDER_TYPE(TmplStruct<bool>);
// Have to explicitely call :
static void declare_TmplStruct(){
    ponder::Class::declare<TmplStruct<int> >()
        .property("field1", &TmplStruct<int>::field1);
    ponder::Class::declare<TmplStruct<short> >()
        .property("field1", &TmplStruct<short>::field1);
    ponder::Class::declare<TmplStruct<bool> >()
        .property("field1", &TmplStruct<bool>::field1);
}
```
Is there an other way to use `PONDER_TYPE` ?

What I am looking for is a way to avoid to declare each concrete types. Types which are referenced from a `.property` call could be automatically declared, I guess.
Anyway, I will look at the doc carefully.

**Comment by billyquith** [comment]
I added an example in [the docs](https://billyquith.github.io/ponder/eg_page_declare.html). I'll close this unless there are further questions.
