### ISSUE TITLE
Support for creating objects in preallocated memory (catchphrase "placement new")

### ISSUE THREAD

**Issue by Weeena** [billyquith/ponder#16]
We would like to be able to create objects with ponder in preallocated memory. We would like this to work for objects for which we know just the class name but not the class definition (i.e. we do not have the class's header file available). For this to work, we would need the following functionalities:
- Construct() calls which we could pass a pointer to some preallocated memory, which internally constructs the desired object with placement new
- Some function with which we could get the size of the object (such that we can placement-new other objects adjacently in our preallocated memory)
- When a placement-new-constructed object is to be released, only its deconstructor should be called but the memory must not be deleted

Would it be possible to extend ponder with the above functionalities?

**Comment by billyquith** [comment]
I think this is doable. Will have a look tomorrow.

**Comment by billyquith** [comment]
This has been added to the 1.1 branch.
