### ISSUE TITLE
File test/userproperty.hpp missing?

### ISSUE THREAD

**Issue by iwbnwif** [billyquith/ponder#19]
Is there supposed to be a file `userproperty.hpp` in the test folder?

It looks like this is included from `test/userproperty.cpp` to setup object `MyClass`.

I would like to see how this is done because I would like to have extra property classes, specifically `wxDateTime` like this:

```
struct ItemInfo
{
    int ID;
    std::string name;
    std::string fileName;
    wxDateTime created;
    etc.
};
```
It probably is already covered in the `Composed*` structures of the `UserObject` test, but it would be good to see anyway.

**Comment by billyquith** [comment]
Thanks. Must have been missed in the refactoring to Catch.
