### ISSUE TITLE
Using as a component in a larger project

### ISSUE THREAD

**Issue by Alicemargatroid** [billyquith/ponder#22]
Normally, with CMake, we simply set a few options and then add an ADD_SUBDIRECTORY

Is there any way to use this in such a way? I'm attempting to use it along with GWork, but it doesn't seem to be working well.

**Comment by billyquith** [comment]
What seems to be the problem? What errors are you getting?

**Comment by Alicemargatroid** [comment]
CMake Error at Libraries/ponder/CMakeLists.txt:42 (include):
  include could not find load file:

    /home/ren/Desktop/Alice2D/cmake/Config.cmake


CMake Error at Libraries/ponder/CMakeLists.txt:43 (include):
  include could not find load file:

    /home/ren/Desktop/Alice2D/cmake/PackageFilename.cmake


Generate version.hpp
CMake Error: File /home/ren/Desktop/Alice2D/version.in does not exist.
CMake Error at Libraries/ponder/CMakeLists.txt:179 (configure_file):
  configure_file Problem configuring file


-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Error at /usr/share/cmake-3.5/Modules/WriteBasicConfigVersionFile.cmake:53 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CMakePackageConfigHelpers.cmake:220 (write_basic_config_version_file)
  Libraries/ponder/CMakeLists.txt:233 (write_basic_package_version_file)

**Comment by Alicemargatroid** [comment]
This is after including Ponder via ADD_SUBDIRECTORY(Libraries/ponder)

It looks like it's looking for your files in my directories; is there a different way to include Ponder? 
Maybe FindPonder?

**Comment by billyquith** [comment]
I've removed the "utils" from Gwork that relies on Ponder. Hopefully you should no longer get this problem.

**Comment by Alicemargatroid** [comment]
@billyquith Thank you for the quick response; I'll test out quickly.
