### ISSUE TITLE
After a UserObject is destroyed or destructed it should be empty

### ISSUE THREAD

**Issue by Weeena** [billyquith/ponder#23]
After a UserObject is destroyed or destructed, e.g.
```
someClass.destroy(someObject);
```
the object sould be empty (i.e. equal to `UserObject::nothing`). This is now not the case, e.g. the member `m_class` still refers to the destroyed object's class.

**Comment by billyquith** [comment]
Do you have a code sample to demonstrate this? The object has been destroyed, it is not useable.

**Comment by billyquith** [comment]
Ok, if you get latest a I think this is fixed.
