### ISSUE TITLE
Change ponder::Type to enum class

### ISSUE THREAD

**Issue by billyquith** [billyquith/ponder#26]
```cpp
enum Type
{
    noType,     ///< No type has been defined yet
    boolType,   ///< Boolean type (bool)
    intType,    ///< Integer types (unsigned/signed char short int long)
    realType,   ///< Real types (float, double)
    stringType, ///< String types (char*, std::string)
    enumType,   ///< Enumerated types
    arrayType,  ///< Array types (std::vector, std::list, T[])
    userType    ///< User-defined classes
};
```

to:

```cpp
enum class Type
{
    none,   ///< No type has been defined yet
    bool,   ///< Boolean type (bool)
    int,    ///< Integer types (unsigned/signed char short int long)
    real,   ///< Real types (float, double)
    string, ///< String types (char*, std::string)
    enum,   ///< Enumerated types
    array,  ///< Array types (std::vector, std::list, T[])
    user    ///< User-defined classes
};
```

**Comment by iwbnwif** [comment]
Is there any way of making this extensible? 

I don't think it is possible, but thought I would ask the question.

One of the problems I have come up against is having multiple "user" types. It would be really nice if ponder::Value::type returned _which_ user type it contains.

**Comment by billyquith** [comment]
Well you get can get the class information from a UserObject?

**Comment by iwbnwif** [comment]
Sorry for the slow response.

Actually, I forgot exactly the situation where I had problems with this, but I think it was something like:
```
... iterate through all members of a ponder::Class ...

switch (thisClass.property(i).type())
{
    case ponder::stringType:
        doSomething ();
        break;
    
    case ponder::userType:
        doSomethingElse ();
        break;
}
```

I think I was missing a way to get the _class_ of the userType for a given property.

**Comment by billyquith** [comment]
The property is abstract/generic. There is a `ClassVisitor` which uses the visitor pattern to allow you to get the details.

**Comment by iwbnwif** [comment]
Sorry, this was my mistake (again). 

Thank you for your hint, I can see from the `ClassVisitor `example that there is a `ponder::UserProperty::getClass() ` method which I can use to get at least the string identification for the class.

**Comment by billyquith** [comment]
Don't worry about it. There are some aspects of this API that seem quite complicated. Perhaps look at the docs and see if they can be improved.
