### ISSUE TITLE
[Question] camp-lua equivalent?

### ISSUE THREAD

**Issue by kkitsune** [billyquith/ponder#27]
Hi! Back in the days of Tegesoft, there was an extension/plugin for Camp that bound it and Lua together. Is it still possible to do with Ponder? Anybody still has the source of this project or could help me do it (I'm not an expert with Lua)?
Thanks

**Comment by billyquith** [comment]
Hi, I didn't know that camp-lua existed. If you have any details of that or other related work I would be interested to know any details. Source code snippets, docs, features, etc. 

I started a Lua binding from ponder metadata in the Lua branch. It is currently incomplete.

**Comment by billyquith** [comment]
I'm going to consider this answered and close it. Will try and get back to the Lua work soonish.
