### ISSUE TITLE
operator overloads supported?

### ISSUE THREAD

**Issue by underdoeg** [billyquith/ponder#33]
I couldn't find anything in the docs. Can ponder also handle operator overloads?

**Comment by billyquith** [comment]
In what sense? Can you register a function that is an operator overload? Yes. Can you call it using operator overload notation? No, the API is different, not C++.

**Comment by underdoeg** [comment]
In the sense that I'll know afterwards that this is an operator overload when I look at the class description?

**Comment by billyquith** [comment]
You could add a tag to it to denote this. There is not specified format for that. You can add arbitrary data to members.

**Comment by underdoeg** [comment]
ok. thx
