### ISSUE TITLE
File include\ponder-xml\common.inl currently does not compile

### ISSUE THREAD

**Issue by Weeena** [billyquith/ponder#35]
Just as a note: The file `include\ponder-xml\common.inl` currently does not comile because it still contains the old types, e.g.

``` C++
else if (property.type() == arrayType)
```

**Comment by billyquith** [comment]
TBH I'm thinking of refactoring that and perhaps removing it.

**Comment by billyquith** [comment]
Do you use this code? If not, there is no urgency to fix it.

**Comment by Weeena** [comment]
No, we do not use this code. But it is rather instructive in showing how generic serialisation may be implemented.

**Comment by billyquith** [comment]
This has been refactored as part of #43. Closing.
