### ISSUE TITLE
Rename PONDER_RTTI

### ISSUE THREAD

**Issue by billyquith** [billyquith/ponder#36]
This macro is used to allow dynamic casting within a class hierarchy. Docs:

> Macro used to activate the Ponder RTTI system into a hierarchy of classes

The name therefore seems a little misleading. Suggestions?

Perhaps `PONDER_DYNAMIC`?

**Comment by Weeena** [comment]
Maybe PONDER_POLYMORPHIC? Or PONDER_THIS_TYPE?

The irony with PONDER_DYNAMIC would be that this macro establishes the static type of a class...

**Comment by billyquith** [comment]
I'm favouring `PONDER_POLYMORPHIC`. That is really the sole reason to use it.

**Comment by billyquith** [comment]
Done.
