### ISSUE TITLE
Serializing Ponder Objects (XML / JSON)

### ISSUE THREAD

**Issue by iwbnwif** [billyquith/ponder#43]
Hi, thank you for your continued efforts on this project.

There is a subfolder `include/ponder-xml` but as far as I can tell these features are not included in the documentation.

Actually, the methods `serialize`and `deserialize` (with the RapidXML compatibility layer) appear to do exactly what I need, but it would be even better if there was a RapidJSON alternative!

Do you think it would be possible to:
1. Include the serialization methods in the documentation.
2. Provide a small round-trip example.
3. Consider an enhancement to also provide a [Rapid]JSON compatibility layer.

**Comment by billyquith** [comment]
This is related to issue #35. I think adding a JSON alternative is  a good idea. I also want to drop support for so many (and many old) XML libraries. 

Pretty busy at the moment but this functionality will be useful to me soon.

**Comment by billyquith** [comment]
I looked at some JSON libraries.
https://github.com/miloyip/nativejson-benchmark

https://github.com/nlohmann/json is header only and ideally I'd use this but it fails on some compilers with spotty C++11 support, like GCC <4.9. Shame.

RapidJSON attractive. Code size is a little large.

PicoJSON does seem to be a good compromise although haven't tested it thoroughly.

Ideally I'd include a header only JSON library internally and have user callbacks for any data validation. JSON and XML could be two default storage formats using the same factories and traversal.

**Comment by iwbnwif** [comment]
> RapidJSON attractive. Code size is a little large
> PicoJSON does seem to be a good compromise although haven't tested it thoroughly

Another one that you may care to look at is cJSON [here](https://github.com/DaveGamble/cJSON). I only came across it because it was mentioned by the author of CodeLite that they are using it. Positives are ANSI C (so shouldn't be too many compiler issues), MIT and actively maintained.

**Comment by billyquith** [comment]
- [JSON parser benchmarks](https://github.com/miloyip/nativejson-benchmark)
