### ISSUE TITLE
int value conversion for hex

### ISSUE THREAD

**Issue by vms1966** [billyquith/ponder#52]
Hi all,
I suggest a small enhancement which adds support for calling functions with hex or oct arguments, in using the std::stol function for that, by just changing the call in line 64 to
std::stol(from.c_str(),0,0), the third argument defines the base (default 10, 0 means interpreting strings with prefix 0x or 0X as hex and prefix 0 as octal).
Best, and thanks Billy for starting and maintaining this very useful library
Mat

**Comment by billyquith** [comment]
How a about providing a patch! Then you'd get a contrib recognition! 🍻 

Actually I'm working on v2. Quite a lot of changes. Trying to get rid of a few "warts" from the existing system. Taking a bit longer than anticipated. The change above won't affect this. I'm pruning some of the stuff which I can't see a use for and trying to simplify some other bits. Quite hard refactoring a piece of code of this complexity so some bits need reworking. Perhaps I should start a ticket asking what people are using Ponder for. After this work I'm going to have to get stuck into my own project as I'm way behind schedule.
