### ISSUE TITLE
Should Class::name() return const Id& rather than IdRef?

### ISSUE THREAD

**Issue by Weeena** [billyquith/ponder#60]
I had the following problem: I wanted to write something like this
```C++
THROW("Unexpected type: " + class.name());
```
Alas, that did not compile because `name()` returns a `string_view` and `string_view` does not support the required `operator+`. As a workaround, I can write
```C++
THROW("Unexpected type: " + std::string(class.name()));
```
but, to be honest, I dont like that very much (and I guess it causes an extra copy).

Since internally, `Class` stores its name as an `Id` (which is identical to `std::string`), I suggest to replace the current
```C++
IdRef name() const;
```
with
```C++
const Id& name() const;
```
Advantage: No unnecessary restrictions are caused.

**Comment by billyquith** [comment]
That makes sense.

**Comment by billyquith** [comment]
In master.
