### ISSUE TITLE
Errors and warnings when building with Visual Studio 2015

### ISSUE THREAD

**Issue by AntAgna** [billyquith/ponder#76]
I experienced a few errors and warnings when compiling master with Visual Studio 2015.

- Name collision with `free` and `new` macros when using memory leak detection
- Two minor warnings in format.cpp
- Type conversion warning (int to wchar_t) in format.cpp
- `bad_conversion` class uses non public inheritance of `std::exception` caused warnings C4673 and C4670

The last one is a significant bug since it means exceptions would not have been caught by `catch (const std::exception& e)`.

**Comment by billyquith** [comment]
> Name collision with free and new macros when using memory leak detection

Hopefully you didn't find any leaks. I haven't  tested for them myself.

**Comment by billyquith** [comment]
> Type conversion warning (int to wchar_t) in format.cpp

Thanks for your work here but I think I may just remove fmt and use iostream. See #59. Just one less dependency.

**Comment by AntAgna** [comment]
I have seen no leaks
