### ISSUE TITLE
Error while compiling ponder in x64 (Visual Studio 2017 CMSVC 14.10.25017)

### ISSUE THREAD

**Issue by w0dm4n** [billyquith/ponder#78]
Hello,
When building on x86 the egtest are working correctly.
On x64 there is some symbol error, the other projects like the .dll are compiling but are not usable
Screen: https://gyazo.com/d1320a2803b8879e52614ddd2c42a295

EDIT:
Just tried with CAMP and its working...

![d1320a2803b8879e52614ddd2c42a295](https://cloud.githubusercontent.com/assets/1754471/25660472/44743efa-3004-11e7-9fab-18a0ac1d308f.png)

**Comment by billyquith** [comment]
Thanks for reporting. I'm removing the format library in Ponder 2.2, see #59. I'll look into the other.

**Comment by billyquith** [comment]
This is done.
