### ISSUE TITLE
missing Class::construct

### ISSUE THREAD

**Issue by michaelaeriksen** [billyquith/ponder#79]
The documentation tells me to create objects like this

 * MyClass* obj = metaclass.construct<MyClass>();
 * metaclass.destroy(obj);

but I can't find the construct or destroy method in the Class class! And it looks like all tests have been commented out that uses that!

So what is the right way to instantiate an object from a metaclass?

**Comment by billyquith** [comment]
Oops, yes the project home page, is stale. The code has changed.

See the project simple example, which is in the docs: https://billyquith.github.io/ponder/docs/index.html

**Comment by alexander-v** [comment]
```cpp
template <typename T>
struct ValueProviderImpl<T*, ValueKind::User>
{
    T* operator()() {return classByType<T>().construct().template get<T*>();}
};
 ```
in https://github.com/billyquith/ponder/blob/master/include/ponder/detail/valueprovider.hpp#L87
doesnt compile
