### ISSUE TITLE
How to find the type of a property

### ISSUE THREAD

**Issue by shierei** [billyquith/ponder#81]
Is there a way to find the type of a property value? I am trying to convert any UserObject's properties into a JSON document. To do that I need to find the type of a property value returned form get() to see if it is a number, string or boolean.

**Comment by shierei** [comment]
I found that there is a kind() member function in ponder::Property for this.

**Comment by billyquith** [comment]
Yes: [docs](https://billyquith.github.io/ponder/docs/classponder_1_1_property.html)
