### ISSUE TITLE
Clang 4.0 compile error:  value of type 'int' is not implicitly convertible to 'ponder::ValueKind' struct ValueProviderImpl<T*, Type>

### ISSUE THREAD

**Issue by Wonkyu-Lee** [billyquith/ponder#84]
detail/valueprovider.hpp line 75

in clang 4.0:
error: value of type 'int' is not implicitly convertible to 'ponder::ValueKind' struct ValueProviderImpl<T*, Type>

I suggest to change type parameter 'int' to 'ValueKind':
before:
```cpp
template <typename T, int Type>
struct ValueProviderImpl<T*, Type>
```
after:
```cpp
template <typename T, ValueKind valueKind>
struct ValueProviderImpl<T*, valueKind>
```

**Comment by billyquith** [comment]
In develop branch. Will appear in next release. Thanks!
