### ISSUE TITLE
Version 2.0 of Ponder is not available anymore.

### ISSUE THREAD

**Issue by jtschea** [billyquith/ponder#86]
Dear developers,

We were using Ponder in version 2.0 which is not available anymore on the GitHub project page. Is there a reason for removing this version? The blog states that version 2.1 is the latest. Where can I find these versions?

Thanks in advance,
Jupp

**Comment by billyquith** [comment]
Apologies. I deleted it as there were issues reported with it. I'd try and use master if I were you. Fixes tend to go straight into master.

TBH I need to adopt a proper release strategy. I've largely just added the versions as a mark of progress.

**Comment by jtschea** [comment]
Thank you very much, Billy, for explaining this and for the work you've done.
Adopting a proper release strategy sounds very promising since Camp/Ponder is a key technology in our quite mature software project that we're using in a professional environment.
Using the master branch is a little bit risky for us. We're building our dependencies as a part of our own build process cloning every component from scratch. With this we wouldn't be able to deploy a constant release. For us it would be good to have Ponder releases (2.0, 2.1, ...) even if they are still containing bugs. At least our releases are always containing bugs ;)

Best regards,
Jupp

**Comment by billyquith** [comment]
Thanks for the feedback. - I've created a V2.0.0 branch. It isn't at exactly the same point as the tag. Looking at the history I update the log and made a few more changes after the tag. I'll leave the 2.0.0 tag where is it is for now.  V2.0 will only receive essential fixes, and user patches. 

Generally, the direction is to separate the meta data from users of the meta data. Ponder had heavy coupling between the metadata and "runtime" usage of it, e.g. invocation of functions. This then allows other users of the metadata, e.g. the Lua use that is in master.

**Comment by jtschea** [comment]
Dear Billy,
Thank you very much for working this out so quickly. 

The Gitflow Workflow is _exactly_ what we're using together with the excellent Atlassian tool chain. Another good documentation on this topic can be found [here](https://www.atlassian.com/git/tutorials/comparing-workflows).

The first thing I will try out Monday morning is version 2.1 :)

Best regards,
Jupp

**Comment by billyquith** [comment]
Thanks. I'll take a look at the git workflow. This project, and Gwork, started out as an exercise in C++11 and refactoring, but it's interesting developing an open source workflow. Useful for encouraging the correct  application of user patches as well.

**Comment by billyquith** [comment]
Since you haven't got back about 2.1 I'm assuming no news is good news! I'll close this ticket. Please open another if you get any hitches.
