### ISSUE TITLE
cmake namespace ponder  -> Ponder

### ISSUE THREAD

**Issue by leolchat** [billyquith/ponder#95]
It seems to be that usually the namespace of libraries from a cmake package is the package name. In ponder, the case is different, making it kind of unusual/weird. Moreover, if one forget to find the package first, cmake error will hint to do a `find_package(ponder)` which won't work.

**Comment by billyquith** [comment]
Nice hat! I find a lot of inconsistencies between cmake find packages. Is the canonical version documented somewhere? I have to admit, when I've needed one, I've just modified one with an appropriate licence.

**Comment by billyquith** [comment]
Done.
